name: qiskit-env

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - black
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - pytables
  - jupyter
  - pip:
    - qiskit[visualization]
    - fire